### ISSUE TITLE
在边录边转模式中，录音中的最后一小段音频没有转码到mp3中，但是在caf中是有的！

### ISSUE THREAD

**Issue by iMinger** [CivelXu/iOS-Lame-Audio-transcoding#1]
在边录边转模式中，录音中的最后一小段音频没有转码到mp3中，但是在caf中是有的！

**Comment by xiaohuapunk** [comment]
同样的问题，发现转格式的mp3文件丢失了1秒，猜测可能是因为结束录音的时候转码也会停止，此时可能源文件数据还没有写入完毕，导致丢失了最后的1秒时间，暂时解决方案，录音结束后，延时一秒后在停止转码的操作
```
/**
 send end record signal
 */
- (void)sendEndRecord {
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        self.stopRecord = YES;
    });
}
```

**Comment by CivelXu** [comment]
@xiaohuapunk 你好, 感谢你的反馈; 我刚才有做一些调整; 
重新做了逻辑判断; 结束的时候判断是否还有剩余的pcm未进行转码

**Comment by xiaohuapunk** [comment]
你好，感谢能及时响应，经测试问题依旧存在，测试机 iPhone 5s  iOS12.2

**Comment by CivelXu** [comment]
@xiaohuapunk 麻烦检查一下, 是不是更新到了我最新修改的代码; 原来的问题是停止录制的时候, 立刻暂停了转码, 这个时候有一部的pcm还没有完全转换完成; 现在加入了 isSleep 标识; 能确保所有的 pcm 完成转码; 我在Demo中 测试的是没有问题的;

**Comment by xiaohuapunk** [comment]
您好大佬，我确定是更新的最新代码，不知是否是因为设备的性能原因导致的，方便QQ联系吗 958439724

**Comment by xiaohuapunk** [comment]
查看录音文件发现 mp3文件确实少了1秒

![image](https://user-images.githubusercontent.com/9956517/55463895-8ca9d180-562c-11e9-81f5-f931c890ea87.png)
![image](https://user-images.githubusercontent.com/9956517/55463915-97646680-562c-11e9-8dfe-441c9b1323ef.png)

**Comment by CivelXu** [comment]
@xiaohuapunk 重新修改了一些 把 [NSThread sleepForTimeInterval:0.05]; 删掉试试;
不确定是不是线程休眠对这里会有一定影响;

**Comment by xiaohuapunk** [comment]
你好，此问题修复了，发现是因为停止录音时 判断 length 不够 PCM_SIZE * 2 导致漏转的问题，已提pr
https://github.com/CivelXu/iOS-Lame-Audio-transcoding/pull/2

**Comment by monologue555** [comment]
经测试问题依旧存在！
