### ISSUE TITLE
你好 lame.framework 是来自开源的框架吗？

### ISSUE THREAD

**Issue by jj89757hhb** [CivelXu/iOS-Lame-Audio-transcoding#4]

**Comment by CivelXu** [comment]
https://sourceforge.net/projects/lame/files/lame/3.100/
是的呢 需要自己编译

**Comment by jj89757hhb** [comment]
你好 我想问个不解的问题：我现在使用你的库 ，发现如果声道数改成1  [dicM setObject:@(1) forKey:AVNumberOfChannelsKey]
那么录制的音频时长变成二分之一？ 这个是什么情况呢？

**Comment by CivelXu** [comment]
@jj89757hhb 这个好久没有研究了，不太清楚，需要你自己来研究一下了。
